## AlmaLinux 10.1 tunings

# alternatives configuration overriding the defaults

PREFERRED_RPM_RPROVIDER_virtual/glibc-langpack-en_or_glibc-all-langpacks = "glibc-langpack-en"
PREFERRED_RPM_RPROVIDER_virtual/glibc-langpack_eq_2.39-58.el10_1.7.alma.1 = "glibc-langpack-en"

PREFERRED_RPM_RPROVIDER_virtual/libtiffxx.so.6___64bit_ = "libtiff"
PREFERRED_RPROVIDER_virtual/libtiffxx.so.6___64bit_ = "libtiff"

PREFERRED_RPM_RPROVIDER_virtual/libgccjit.so.0___64bit_ = "libgccjit"
PREFERRED_RPROVIDER_virtual/libgccjit.so.0___64bit_ = "gcc"
PREFERRED_RPROVIDER_virtual/libsframe.so.1___64bit_ = "binutils"

# FIXME: shouldn't those covered by meta-almalinux/conf/default-providers.conf ?

PREFERRED_RPROVIDER_virtual/SDL2_x86-64__ge_2.0.18 = "sdl2-compat"
PREFERRED_RPROVIDER_virtual/libSDL2-2.0.so.0___64bit_ = "sdl2-compat"
PREFERRED_RPROVIDER_virtual/environment_modules_ = "environment-modules"

# 10.0 still provides a few obsolete SRPMS

PREFERRED_RPROVIDER_virtual/tex_doc.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_exscale.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_fix-cm.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_fixltx2e.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_flafter.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_fontenc.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_ifthen.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_inputenc.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_latexsym.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_makeidx.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_oldlfont.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_shortvrb.sty_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_t1cmr.fd_ = "texlive"
PREFERRED_RPROVIDER_virtual/tex_textcomp.sty_ = "texlive"


## break dependency loops

RDEPENDS:almalinux-repos:remove = "almalinux-release"
RDEPENDS:binutils-gold:remove = "binutils"
RDEPENDS:ca-certificates:remove = "virtual/coreutils"
RDEPENDS:git:remove = "perl-Git"
RDEPENDS:glibc-common:remove = "glibc bash"
RDEPENDS:glibc-gconv-extra:remove = "glibc"
RDEPENDS:glibc-langpack-en:remove = "glibc"
RDEPENDS:libxcrypt-devel:remove = "glibc-devel"
RDEPENDS:openssl-libs:remove = "openssl-fips-provider"
RDEPENDS:perl-B:remove = "perl-Data-Dumper"
RDEPENDS:perl-Exporter:remove = "perl-Carp"
RDEPENDS:perl-Getopt-Long:remove = "perl-Pod-Usage"
RDEPENDS:perl-IO-Socket-SSL:remove = "perl-HTTP-Tiny"
RDEPENDS:perl-libs:remove = "perl-DynaLoader"
RDEPENDS:perl-libs:remove = "perl-Encode"
RDEPENDS:perl-libs:remove = "perl-PathTools"
RDEPENDS:perl-libs:remove = "perl-Carp"
RDEPENDS:perl-libs:remove = "perl-Exporter"
RDEPENDS:perl-libs:remove = "perl-Getopt-Std"
RDEPENDS:perl-libs:remove = "perl-Getopt-File-Basename"
RDEPENDS:perl-podlators:remove = "perl-Pod-Usage"
RDEPENDS:perl-POSIX:remove = "perl-locale"
RDEPENDS:redhat-rpm-config:remove = "pyproject-srpm-macros"
RDEPENDS:redhat-rpm-config:remove = "python-srpm-macros"
RDEPENDS:redhat-rpm-config:remove = "go-srpm-macros"
RDEPENDS:redhat-rpm-config:remove = "fonts-srpm-macros"
RDEPENDS:redhat-rpm-config:remove = "forge-srpm-macros"
RDEPENDS:rpm-libs:remove = "rpm"
RDEPENDS:systemd-pam:remove = "systemd"
