## AlmaLinux 10.0 tunings

# alternatives configuration overriding the defaults

PREFERRED_RPROVIDER_virtual/glibc-langpack-en_or_glibc-all-langpacks = "glibc-langpack-en"
PREFERRED_RPROVIDER_virtual/glibc-langpack_eq_2.39-46.el10_0.4.alma.1 = "glibc-langpack-en"
