# File copied from the one generated by gen-dnf-proxy.py for 10.2, Aug 24 11:33 2026
# Adjusted for mirror URLs

EPELSRC_MIRROR = "https://dl.fedoraproject.org/pub/epel/10.2/Everything/source/tree"
EPEL_MIRROR = "https://dl.fedoraproject.org/pub/epel/10.2/Everything"
EPEL_ALTARCH_MIRROR = "https://epel.repo.almalinux.org/10.2"

# Original contents follows

inherit dnf-bridge

PN = "libcgroup"
PV = "3.0"
PR = "10.el10_2"
PACKAGES = " \
 libcgroup \
 libcgroup-devel \
 libcgroup-pam \
 libcgroup-tools \
 "

URI_src = "${EPELSRC_MIRROR}/Packages/l/libcgroup-3.0-10.el10_2.src.rpm;name=src;unpack=0"
SRC_URI = "${URI_src}"
SRC_URI[src.sha256sum] = "cc4ad7abb3e2a133c8efdf0d4a9743ce167506af17b2aef8a746b44fca754a33"

URI_x86_64_v2_libcgroup = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/libcgroup-3.0-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_libcgroup;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libcgroup}"
SRC_URI[x86_64_v2_libcgroup.sha256sum] = "a67cbe4897425799542e8df6fe5a4ab0966353989815e62046b33699fefa38e9"

URI_x86_64_v2_libcgroup-devel = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/libcgroup-devel-3.0-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_libcgroup-devel;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libcgroup-devel}"
SRC_URI[x86_64_v2_libcgroup-devel.sha256sum] = "53d408e398cb4126eb8e2a4fa363ea849eef7128bf5736d7a6c5b0dffd5404e0"

URI_x86_64_v2_libcgroup-pam = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/libcgroup-pam-3.0-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_libcgroup-pam;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libcgroup-pam}"
SRC_URI[x86_64_v2_libcgroup-pam.sha256sum] = "8d971e5a58db815e189072c546296f4458d326d3bc11f7a1acb87dc85c423a6e"

URI_x86_64_v2_libcgroup-tools = "${EPEL_ALTARCH_MIRROR}/x86_64_v2/Packages/libcgroup-tools-3.0-10.el10_2.alma_altarch.x86_64_v2.rpm;name=x86_64_v2_libcgroup-tools;unpack=0"
SRC_URI:append = " ${URI_x86_64_v2_libcgroup-tools}"
SRC_URI[x86_64_v2_libcgroup-tools.sha256sum] = "cdda48216bc48cbce52e9ee4cda586ee617f96bfceef2e3ec9535ac1cba9727b"

URI_aarch64_libcgroup = "${EPEL_MIRROR}/aarch64/Packages/l/libcgroup-3.0-10.el10_2.aarch64.rpm;name=aarch64_libcgroup;unpack=0"
SRC_URI:append = " ${URI_aarch64_libcgroup}"
SRC_URI[aarch64_libcgroup.sha256sum] = "d6b7e57acf3b9bfe429631fa136933eebc0fdca591051ab52dfb675a47fa9e95"

URI_aarch64_libcgroup-devel = "${EPEL_MIRROR}/aarch64/Packages/l/libcgroup-devel-3.0-10.el10_2.aarch64.rpm;name=aarch64_libcgroup-devel;unpack=0"
SRC_URI:append = " ${URI_aarch64_libcgroup-devel}"
SRC_URI[aarch64_libcgroup-devel.sha256sum] = "3741315902c143af33b8ac9e496052f3c3507ef9b958a8f225f8226dd629105a"

URI_aarch64_libcgroup-pam = "${EPEL_MIRROR}/aarch64/Packages/l/libcgroup-pam-3.0-10.el10_2.aarch64.rpm;name=aarch64_libcgroup-pam;unpack=0"
SRC_URI:append = " ${URI_aarch64_libcgroup-pam}"
SRC_URI[aarch64_libcgroup-pam.sha256sum] = "58518849918fbcfdeca2ca51e79e7c83561b95a5fa601cca0740ce33f7de5739"

URI_aarch64_libcgroup-tools = "${EPEL_MIRROR}/aarch64/Packages/l/libcgroup-tools-3.0-10.el10_2.aarch64.rpm;name=aarch64_libcgroup-tools;unpack=0"
SRC_URI:append = " ${URI_aarch64_libcgroup-tools}"
SRC_URI[aarch64_libcgroup-tools.sha256sum] = "fc52cd27612ae36ffa23195482c498601abb09b07b6b4990b936f05a10749281"

RDEPENDS:libcgroup = " \
 bash \
 glibc \
 shadow-utils \
 systemd \
 "
RDEPENDS:libcgroup-devel = " \
 libcgroup \
 pkgconf-pkg-config \
 "
RDEPENDS:libcgroup-pam = " \
 glibc \
 libcgroup \
 pam-libs \
 "
RDEPENDS:libcgroup-tools = " \
 bash \
 glibc \
 libcgroup \
 systemd \
 "
